# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRouter < Formula
  desc "Adaptive OpenAI-compatible LLM router with prompt classification"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-router"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.5/hyper-mcp-router-aarch64-apple-darwin.tar.gz"
      sha256 "3e22e7ace446de40eccbfc5822e36872838250283ca795eb52ee831faac9075c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.5/hyper-mcp-router-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a1a1a9d3350ddefa1376cab88402cd63ddd438a6aed198be68e1b0e8cb0e1259"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.5/hyper-mcp-router-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "80901c0e6760dc174521bcc6a30d689da20b9b08907fa195ad3a6f329c2ead17"
    end
  end

  def install
    bin.install "hyper-mcp-router"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-router --version")
  end
end
