# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcp < Formula
  desc "A fast, secure MCP server that extends its capabilities through WebAssembly plugins"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.1/hyper-mcp-aarch64-apple-darwin.tar.gz"
      sha256 "96d3cb40d48ed8d7ed68f96884950d9655c87ec5af2a7efce95b2a290291416e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.1/hyper-mcp-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d44447bf73fd4fd8d1f15bd13dab260e7ca34043a4ba2ebe90eae1dec2591568"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.1/hyper-mcp-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "18d25bef603be382ca518e9cfcaceeef15860f5e302a8088b6a25583da38071b"
    end
  end

  def install
    bin.install "hyper-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp --version")
  end
end
