# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcp < Formula
  desc "A fast, secure MCP server that extends its capabilities through WebAssembly plugins"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.0/hyper-mcp-aarch64-apple-darwin.tar.gz"
      sha256 "ad4cfa110edaa2de608f9fa8b7910815b0b622e0bbdaea641b32a8576e1d9ca5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.0/hyper-mcp-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "30e34048b8a8c395755fecc52323ee7ef201087b5e14c1760a3e17dc28cef74a"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.8.0/hyper-mcp-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4e780770b26ef6fad20a71d05d499b0b220d566f364e82585beca30f67c666d9"
    end
  end

  def install
    bin.install "hyper-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp --version")
  end
end
