# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpProxy < Formula
  desc "Streamable-HTTP to Stdio MCP proxy"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-proxy"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.3/hyper-mcp-proxy-aarch64-apple-darwin.tar.gz"
      sha256 "67b34e2234e61349ba0035c3c733d7314b85f730f179930e31b18cf88b67a6a3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.3/hyper-mcp-proxy-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f3479a88a1e3802629675e3b5538aa599ba4cbf57173e360930c1964e14aa0b5"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.3/hyper-mcp-proxy-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a01e5535d9b83268964be3ec1b1a4f5c0d3bf0ba7267948fd16a29a23fd2609d"
    end
  end

  def install
    bin.install "hyper-mcp-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-proxy --version")
  end
end
