# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRouter < Formula
  desc "Adaptive OpenAI-compatible LLM router with prompt classification"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-router"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.4/hyper-mcp-router-aarch64-apple-darwin.tar.gz"
      sha256 "ac88035f77db2b9bd396631add8afa43806950c761d6eb7424a3ebe7f0491822"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.4/hyper-mcp-router-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "20315607feede572fc067a17ed4e12fdf0e15d7dd392ab00bad2a9122bf314f5"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.4/hyper-mcp-router-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d96a56dbb3d6213e5d20024d5770dc9c441ad0c5563a0e477fdbb5be796c4502"
    end
  end

  def install
    bin.install "hyper-mcp-router"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-router --version")
  end
end
