# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcp < Formula
  desc "A fast, secure MCP server that extends its capabilities through WebAssembly plugins"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp"
  version "0.7.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.7.4/hyper-mcp-aarch64-apple-darwin.tar.gz"
      sha256 "f1f343d226aeaa92b837e1b8088e117449ad89fb15cee3b894cdefde017ce965"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.7.4/hyper-mcp-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cb81d517a6aa6ccbb360958be0d8735d84328c15e880fbc553df1828f33767fe"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp/releases/download/v0.7.4/hyper-mcp-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7548d5417b2afe564230d4841db6a3f2081590fc4dd9b3f574634be45664b098"
    end
  end

  def install
    bin.install "hyper-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp --version")
  end
end
