# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRemote < Formula
  desc "Stdio to Streamable-HTTP MCP proxy with OAuth support"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-remote"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.2.1/hyper-mcp-remote-aarch64-apple-darwin.tar.gz"
      sha256 "b00140fdba94518e5def07806a1a8dadc3d0be6c45ec6b76fd43be373e341479"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.2.1/hyper-mcp-remote-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c3586423032d859a0a6e36626dd4397bbcce07a86a8e4453996474eeac6877ce"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.2.1/hyper-mcp-remote-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c82d9ddcd39cb0245b9e110d4935ae6c0c51844e3f441e0dcfb4a5404e6c03af"
    end
  end

  def install
    bin.install "hyper-mcp-remote"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-remote --version")
  end
end
