# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRemote < Formula
  desc "Stdio to Streamable-HTTP MCP proxy with OAuth support"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-remote"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.1.3/hyper-mcp-remote-aarch64-apple-darwin.tar.gz"
      sha256 "36b4f2d497cb95a71ec185590455e7c291af27dda0891f13c42a7226365df00b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.1.3/hyper-mcp-remote-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bbbb3e62c00edc6ab1ef8b429f450efed2ff49cb2b73477d85b8651ffd71fc51"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.1.3/hyper-mcp-remote-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b8edf99fb161abf5d771e3063045b28df74708890a531c6811f07d3dfeb00aca"
    end
  end

  def install
    bin.install "hyper-mcp-remote"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-remote --version")
  end
end
