# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRemote < Formula
  desc "Stdio to Streamable-HTTP MCP proxy with OAuth support"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-proxy"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.2/hyper-mcp-proxy-aarch64-apple-darwin.tar.gz"
      sha256 "f2d61d62310756667f451b0fd6356a3393d6d4c4ab7dc2a6c51daaf153ec72df"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.2/hyper-mcp-proxy-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f02083622a30a2f0584a1f28b7bb200b93bb7ee79795601cf24aace45cf03147"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-proxy/releases/download/v0.3.2/hyper-mcp-proxy-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fc09cac34001e77757b27d13da21704925844ad5a1347de7d49d9a9d736f8abb"
    end
  end

  def install
    bin.install "hyper-mcp-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-proxy --version")
  end
end
