# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRemote < Formula
  desc "Stdio to Streamable-HTTP MCP proxy with OAuth support"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-remote"
  version "0.3.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.3.4/hyper-mcp-remote-aarch64-apple-darwin.tar.gz"
      sha256 "32d4e7a48ab5769aecbe1b1f8294eb972d068968ef50a88009c17ceb15aed6ef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.3.4/hyper-mcp-remote-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "30e8fb14071ecfe0232d802a3f8bd5283073d100e66ff18e272fbfd11764ed36"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-remote/releases/download/v0.3.4/hyper-mcp-remote-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f0c4bf3d1deb7257757222e74e0dbb5996362e4ae8ebb5670a286062020487ad"
    end
  end

  def install
    bin.install "hyper-mcp-remote"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-remote --version")
  end
end
