# This file is generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class HyperMcpRouter < Formula
  desc "Adaptive OpenAI-compatible LLM router with prompt classification"
  homepage "https://github.com/hyper-mcp-rs/hyper-mcp-router"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.2/hyper-mcp-router-aarch64-apple-darwin.tar.gz"
      sha256 "3fb8c6fc4b68b9b9216b45c3fad4b69cde5bacb0b4132d429575a5657cce3c37"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.2/hyper-mcp-router-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "71747fa681c57962384f4f562c9c669c36dea377b7405c1f25b9e58398cb0caf"
    end
    on_intel do
      url "https://github.com/hyper-mcp-rs/hyper-mcp-router/releases/download/v0.1.2/hyper-mcp-router-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1084f2879a76c82a0652b52c9a5460a1c00b95690e49e9b38ccb769ba82fd6df"
    end
  end

  def install
    bin.install "hyper-mcp-router"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyper-mcp-router --version")
  end
end
